#!/usr/bin/env node
var files = process.argv.slice(2);
if( files.length ) {
  global.I = require('./ihope.js');
  var path = require('path');
  var cwd = process.cwd();
  for(var i=0; i<files.length; i++) {
    var file = path.relative(cwd, files[i]);
    if(file[0]!=='/') file = './' + file;
    global.I.js(file);
  }
}
else {
  console.log('Usage: it your-test.js');
}